// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmltsVyq4ZWyH_ts8TXzXCQuhLQg3ceo4',
    appId: '1:447863742589:web:1bb171831f28e80b811114',
    messagingSenderId: '447863742589',
    projectId: 'cashit-f42d7',
    authDomain: 'cashit-f42d7.firebaseapp.com',
    storageBucket: 'cashit-f42d7.firebasestorage.app',
    measurementId: 'G-FZFXM1EHBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXxRT27iO2TqqvIn28cflAAqoraZo6DkU',
    appId: '1:447863742589:android:5d431bfda517d399811114',
    messagingSenderId: '447863742589',
    projectId: 'cashit-f42d7',
    storageBucket: 'cashit-f42d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARbKNRhIN5nuoq8Q_XXbwC4SmtDO-3OCA',
    appId: '1:447863742589:ios:c4a907486b9e10ea811114',
    messagingSenderId: '447863742589',
    projectId: 'cashit-f42d7',
    storageBucket: 'cashit-f42d7.firebasestorage.app',
    androidClientId: '447863742589-fipieaa6d98kre4e8flp3air2df78ksm.apps.googleusercontent.com',
    iosClientId: '447863742589-rplnurjudtouqnm85cm163hm3avqnttu.apps.googleusercontent.com',
    iosBundleId: 'com.example.cashit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARbKNRhIN5nuoq8Q_XXbwC4SmtDO-3OCA',
    appId: '1:447863742589:ios:c4a907486b9e10ea811114',
    messagingSenderId: '447863742589',
    projectId: 'cashit-f42d7',
    storageBucket: 'cashit-f42d7.firebasestorage.app',
    androidClientId: '447863742589-fipieaa6d98kre4e8flp3air2df78ksm.apps.googleusercontent.com',
    iosClientId: '447863742589-rplnurjudtouqnm85cm163hm3avqnttu.apps.googleusercontent.com',
    iosBundleId: 'com.example.cashit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmltsVyq4ZWyH_ts8TXzXCQuhLQg3ceo4',
    appId: '1:447863742589:web:d4a0d761aa30a167811114',
    messagingSenderId: '447863742589',
    projectId: 'cashit-f42d7',
    authDomain: 'cashit-f42d7.firebaseapp.com',
    storageBucket: 'cashit-f42d7.firebasestorage.app',
    measurementId: 'G-41L5EBEV62',
  );

}